import {
    Code,
    Heart,
    Book,
    Plane,
    Briefcase,
    Palette,
    GraduationCap,
    Utensils,
    Music,
    Gamepad,
    FlaskConical,
    Landmark,
    Leaf,
    Target,
    Smile,
    Shirt,
    Baby,
    Users,
    Camera,
    Flower,
    Hammer,
    Trophy,
    PawPrint,
    Megaphone,
    PenTool,
    PenLine,
    Languages,
    Lightbulb,
    Calendar,
  } from "lucide-react";
export const categories = [
  { icon: Code, text: "Tech" },
  { icon: Heart, text: "Health" },
  { icon: Book, text: "Life" },
  { icon: Plane, text: "Travel" },
  { icon: Briefcase, text: "Business" },
  { icon: Palette, text: "Art" },
  { icon: GraduationCap, text: "Education" },
  { icon: Utensils, text: "Food & Recipes" },
  { icon: Music, text: "Music" },
  { icon: Gamepad, text: "Gaming" },
  { icon: FlaskConical, text: "Science" },
  { icon: Landmark, text: "History" },
  { icon: Leaf, text: "Environment" },
  { icon: Target, text: "Productivity" },
  { icon: Smile, text: "Self-Improvement" },
  { icon: Shirt, text: "Fashion" },
  { icon: Baby, text: "Parenting" },
  { icon: Users, text: "Relationships" },
  { icon: Camera, text: "Photography" },
  { icon: Flower, text: "Gardening" },
  { icon: Hammer, text: "DIY & Crafts" },
  { icon: Trophy, text: "Sports" },
  { icon: PawPrint, text: "Pets" },
  { icon: Megaphone, text: "Marketing" },
  { icon: PenTool, text: "Design" },
  { icon: PenLine, text: "Writing" },
  { icon: Languages, text: "Language Learning" },
  { icon: Lightbulb, text: "Inspiration" },
  { icon: Calendar, text: "Events" },
];
